config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :candidate_job_actions, only: [
                                            :candidate_job_saved,
                                            :candidate_job_viewed,
                                            :candidate_matches,
                                            :candidate_save_job
  ]

  resources :jobs do
    member do
      post :email_match_candidates
    end
  end

  resources :educations, only: [:destroy]

  resources :experiences, only: [:destroy]

  resources :job_candidates, only: [
                                      :withdrawn_job_candidates,
                                      :open_job_candidates,
                                      :receipt,
                                      :shortlist_candidate,
                                      :remove_candidate,
                                      :withdraw,
                                      :accept_candidate,
                                      :apply
                                    ]

  devise_for :employers, :controllers => { :sessions => "employers/sessions", :registrations => "employers/registrations"}
  devise_for :candidates, :controllers => { :sessions => "candidates/sessions", :registrations => "candidates/registrations"}

  get 'candidates/account' => 'candidates#account'
  put 'candidates/account' => 'candidates#update'
  get 'candidates/archetype' => 'candidates#archetype'
  get 'candidates/archetype_result' => 'candidates#archetype_result'
  put 'candidates/archetype' => 'candidates#update_archetype'
  get 'candidates/profile/:id' => 'candidates#profile', as: 'candidates_profile'
  get 'candidates/incognito' => 'candidates#incognito'
  get 'candidates/subscription' => 'candidates#subscription'

  get 'candidates/jobs_saved' => 'candidate_job_actions#candidate_job_saved', as: 'candidate_job_saved'
  get 'candidates/jobs_viewed' => 'candidate_job_actions#candidate_job_viewed', as: 'candidate_job_viewed'
  get 'candidates/candidate_matches' => 'candidate_job_actions#candidate_matches', as: 'candidate_matches'
  post 'candidates/candidate_save_job/:job_id' => 'candidate_job_actions#candidate_save_job', as: 'candidate_save_job'

  get 'my_withdrawn_jobs' => 'job_candidates#withdrawn_job_candidates'
  get 'my_jobs' => 'job_candidates#open_job_candidates'
  get 'job_receipt/:id' => 'job_candidates#receipt', as: 'job_receipt'
  post 'shortlist_candidate/:job_id/:candidate_id' => 'job_candidates#shortlist_candidate', as: 'shortlist_candidate'
  post 'remove_candidate/:job_id/:candidate_id' => 'job_candidates#remove_candidate', as: 'remove_candidate'
  put 'withdraw/:id' => 'job_candidates#withdraw', as: 'withdraw_candidate'
  put 'accept_candidate/:id' => 'job_candidates#accept_candidate', as: 'accept_candidate'
  get 'job_candidates/:id/apply' => "job_candidates#apply", as: "create_job_candidates"

  get 'employers/public/:id' => 'employers#public', as: 'employers_public'
  get 'employers/account' => 'employers#account'
  put 'employers/account' => 'employers#update'
  get 'employers/profile' => 'employers#profile'
  get 'employers/payment_methods' => 'employers#list_payment_method'
  get 'employers/payment/verify' => 'employers#add_payment_method'
  post 'employers/payment' => 'employers#insert_payment_method'
  get 'employers/choose_pay_method' => 'employers#choose_payment_method'

  get 'employer_jobs' => 'jobs#employer_index', as: 'employer_jobs'
  get 'employer_jobs/archive' => 'jobs#employer_archive', as: 'employer_archive_jobs'
  get 'employer_jobs/:id' => 'jobs#employer_show', as: 'employer_show'
  get 'employer_job_actions/:id' => 'jobs#employer_show_actions', as: 'employer_show_actions'
  get 'employer_job_matches/:id' => 'jobs#employer_show_matches', as: 'employer_show_matches'
  get 'employer_job_shortlists/:id' => 'jobs#employer_show_shortlists', as: 'employer_show_shortlists'
  get 'employer_job_remove/:id' => 'jobs#employer_show_remove', as: 'employer_show_remove'
  put 'inactivate_job/:id' => 'jobs#inactivate_job', as: 'inactivate_job'
  get 'employer_job_expired' => 'jobs#list_expired_jobs', as: 'employer_job_expired'
  post 'employer_payment/:id' => 'jobs#pay_to_enable_expired_job', as: 'employer_job_payment'

  root to: 'pages#index'
  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'hustlers' => 'pages#hustlers'
  get 'hirers_faq' => 'pages#hirers_faq'
  get 'hustlers_faq' => 'pages#hustlers_faq'
  get 'privacy_policy' => 'pages#privacy_policy'
  get 'pages/index'
  get 'pages/hustlers'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/hirers_faq'
  get 'pages/hustlers_faq'
  get 'pages/privacy_policy'

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy,
                                 :inactivate_job, :employer_show,
                                 :employer_show_actions, :employer_show_matches,
                                 :employer_show_shortlists, :employer_show_remove,
                                 :email_match_candidates, :pay_to_enable_expired_job]
  before_action :authenticate_employer!, only: [:new, :create, :edit, :update,
                                                 :destroy, :employer_archive,
                                                 :employer_show, :employer_show_actions,
                                                 :employer_show_matches, :employer_show_shortlists,
                                                 :employer_index, :employer_archive,
                                                 :list_expired_jobs, :inactivate_job,
                                                 :employer_show_remove, :email_match_candidates,
                                                 :pay_to_enable_expired_job
                                               ]
  # GET /jobs
  # GET /jobs.json
  def index
    # :(
    redirect_to candidate_matches_path
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    authorize(@job)
    if current_candidate
      @candidate_job_action = CandidateJobAction.where(candidate_id: current_candidate.id,
                                                       job_id: @job.id).first
      if !@candidate_job_action
        current_candidate.view_job(@job)
      end
    end
  end

  # signed_in employer required
  # employer can submit new job
  # GET /jobs/new
  def new
    @job = Job.new
    authorize(@job)
    if params.permit(:copy_id)[:copy_id]
      job_copy = Job.find(params.permit(:copy_id)[:copy_id])
      attributes = job_copy.attributes.select do |attr, value|
        value != nil
      end
      @job.assign_attributes(attributes)
      @job.id = nil
    end
  end

  # signed_in employer required
  # POST /jobs
  # POST /jobs.json
  def create
    job_function = JobFunction.find(job_params[:job_function_id])
    redirect_to :back, notice: 'Oops, the job_function is invalid.' if job_function.nil?
    @job = Job.new(job_params.merge(
                              activated_at: DateTime.now,
                              employer_id: current_employer.id,
                              job_function_id: job_function.id))
    authorize(@job)
    respond_to do |format|
      if @job.save
        tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
        tracker.track('employer-' + @job.employer.email, 'job created')
        format.html { redirect_to employer_archive_jobs_path, notice: 'Job was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # signed_in employer required
  # GET /jobs/1/edit
  def edit
    authorize @job
  end

  # signed_in employer required
  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    authorize(@job)
    job_function = JobFunction.find(job_params[:job_function_id])
    respond_to do |format|
      if @job.update(job_params.merge(archetype_low: job_function.low,
                                      archetype_high: job_function.high,
                                      job_function_id: job_function.id))
        format.html { redirect_to employer_jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # signed_in employer required
  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    authorize(@job)
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # ToDo: remove this later
  # def send_intro
  #   @job = Job.find(params[:id])
  #   @candidate = Candidate.find(params[:candidate_id])

  #   CandidateMailer.send_job_intro(@candidate.email, @job).deliver
  #   render json: :ok
  # end

  # GET: employer_job_actions/:id
  # signed_in employer is required
  # List of all visible candidates who have viewed the job
  def employer_show_actions
    authorize @job
    @candidates = Job.visible_candidate_viewed_list(@job).page(params[:page])
  end

  # GET: employer_job_matches/:id
  # signed_in employer is required
  # List of all candidates whose profile matched with job
  def employer_show_matches
    authorize @job
    @candidates = @job.candidate_matches_list.page(params[:page])
  end

  # GET: employer_jobs/:id
  # signed_in employer is required
  # List of the applications who are not removed and shortlisted
  def employer_show
    authorize @job

    @job.job_candidates.includes(:candidate)
        .where(status: JobCandidate.statuses[:submitted])
        .map { |jc| jc.viewed! }

    @job_candidates = @job.job_candidates.includes(:candidate).where("status NOT IN (?)",
                                                [JobCandidate.statuses[:shortlist],
                                                JobCandidate.statuses[:deleted]])
                                          .page(params[:page])
  end

  # GET: employer_job_shortlists/1
  # signed_in employer is required
  # List of all job_candidates whose profile is shortlisted
  def employer_show_shortlists
    authorize @job
    @shortlists = JobCandidate.includes(:candidate).where(:job_id => params[:id], :status => JobCandidate.statuses[:shortlist]).page(params[:page])
  end

  # GET: employer_job_remove/1
  # signed_in employer is required
  # List of all job_candidates whose profile is rejected or deleted
  def employer_show_remove
    authorize @job
    @removed_job_candidates = JobCandidate.includes(:candidate).where(:job_id => params[:id], :status => JobCandidate.statuses[:deleted]).page(params[:page])
  end

  # signed_in employer is required
  # list all open jobs of signed_in employer, count inactive job and open jobs and display on
  # this page and link count views-matches-applicants-shortlist-removed
  def employer_index
    @jobs = Job.enable.where(employer_id: current_employer.id, is_active: true).page(params[:page])
    @inactive_job_count = Job.enable.where(employer_id: current_employer.id, is_active: false ).count
    @expired_job_count = Job.expired.where(employer_id: current_employer.id).count
  end

  # signed_in employer is required
  # list of inactive jobs, with count of views-matches-applicants
  def employer_archive
    @jobs = Job.enable.where(employer_id: current_employer.id, is_active: false).page(params[:page])
    @active_job_count = Job.enable.where(employer_id: current_employer.id, is_active: true ).count
    @expired_job_count = Job.expired.where(employer_id: current_employer.id).count
  end

  # signed_in employer is required
  # list of employer's job which is expired by admin
  def list_expired_jobs
    @jobs = Job.expired.where(employer_id: current_employer.id).page(params[:page])
    @active_job_count = Job.enable.where(employer_id: current_employer.id, is_active: true ).count
    @inactive_job_count = Job.enable.where(employer_id: current_employer.id, is_active: false ).count
    @customer = current_employer.selected_card
  end

  # toggle is_active
  def inactivate_job
    authorize @job
    @job.is_active = !@job.is_active
    @job.save
    respond_to do |format|
      format.html { redirect_to employer_jobs_path, notice: 'Job was successfully updated.' }
    end
  end

  # Send email to all candidates who matches the job and who have only subscribed to alert feature
  def email_match_candidates
    authorize @job
    result = @job.send_email_to_matched_candidates
    case result
    when 0, 500
      redirect_to employer_show_matches_path(@job.id), notice: 'Email send to all matched candidates who have subscribed to receive email.'
    end
  end

  # pay and enable the job
  # Todo: add test cases
  def pay_to_enable_expired_job
    authorize(@job)
    # customer = current_employer.customer
    customer = current_employer.selected_card
    if customer.nil?
      redirect_to employer_job_expired_path, notice: 'Oops! we cannot process your request,
                                                      we have not found valid card.' and return
    end
    # return if employer does not verify payment method
    service_pay = Services::Pay.new(current_employer, @job)

    if service_pay.is_payment_processed?(customer)
      # now payment is successfully happened, so enable the job,
      # then send email to matched candidates
       @job.update(status: Job.statuses['enable'],
                   activated_at: Time.now)

      # send email to matched candidates
      result = @job.send_email_to_matched_candidates
      case result
      when 0, 500
        redirect_to employer_jobs_path, notice: 'Job is activated and email is sent to
                                                 all matched candidates who have
                                                 subscribed to our job match alert.'
      end
    else
      redirect_to employer_job_expired_path, notice: 'Oops! we cannot process your request,
                                                      please contact techical support.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:distance, :job_function_id,:employer_id, :city, :state_id,
                                :salary_low, :salary_high, :zip, :is_remote, :title, :description,

app/views/jobs/_candidate_sidebar.html.haml
%p
  = link_to "Positions Viewed", candidate_job_viewed_path
%p
  = link_to "Matches", candidate_matches_path
%p
  = link_to "Saved", candidate_job_saved_path

app/views/jobs/_card_js.erb
<script>
  var subscription;

  $(document).ready(function() {
    Stripe.setPublishableKey($('meta[name="stripe-key"]').attr('content'));
    return subscription.setupForm();
  });

  subscription = {
    setupForm: function() {
      return $('#new_user').submit(function() {
        $("#stripe_error").hide();
        $('input[type=submit]').attr('disabled', true);
        subscription.processCard();
        return false;
      });
    },
    processCard: function() {
      var card, charge;
      card = {
        number: $('#card_number').val(),
        cvc: $('#card_code').val(),
        expMonth: $('#card_month').val(),
        expYear: $('#card_year').val()
      };
      return Stripe.createToken(card, subscription.handleStripeResponse);
    },
    handleStripeResponse: function(status, response) {
      if (status === 200) {
        console.log('stripe card token')
        console.log(response.id)
        $('#job_payment_stripe_card_token').val(response.id);
        $('#new_user')[0].submit();
      } else {
        $('input[type=submit]').attr('disabled', false);
        $('#stripe_error').show();
        $('#stripe_error').html(response.error.message)
      }
    }
  };

  function isNumber(which) {
    var val = which.value;
    val = val.replace(/[^0-9]/g, '');  // strip non-digits
    which.value = val;
  }

  $(function(){
    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

    $('#pay-btn').click(function(e) {
      $('#salary_low').val(salary_slider.slider('getValue')[0]);
      $('#salary_high').val(salary_slider.slider('getValue')[1]);
      $('#waiting').show();
      $('#new_user').submit();
    });
  });
</script>

app/views/jobs/_employer_item.html.haml
.panel-container
  .panel-header
    .row
      .col-md-4.col-xs-12
        %p
          Job created
          = format_date(job.created_at)
      .col-md-8.col-xs-12
        .action-bar
          = link_to new_job_path(:copy_id => job.id) do
            %i.fa.fa-plus{title: "copy to a new job"}
          = link_to edit_job_path(job) do
            %i.fa.fa-edit{title: "edit this job"}
          = link_to job, :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %i.fa.fa-trash{title: "delete this job"}
  .panel-content
    = link_to employer_job_path(job) do
      %h2= job.title
      %p.description
        = truncate(job.description,length: 400, omission: "...",)

app/views/jobs/_form.html.haml
= form_for job, :role=>"form", :html => {:id => "new_user"} do |f|
  .field
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .field
    = f.label :description
    = f.text_area :description, class: "wysihtml5", rows: 12
  .field
    %label
      Job Function
    %p Select from the pull down menu to the left the PRIMARY Function for this position.  It is important you choose the best selection for this specific role so that SalesMatchr can make the best matches!
    %br
    = f.collection_select(:job_function_id, JobFunction.all, :id, :name,  {:class => 'form-control'})
  .field
    %label
      Minimum Years of Experience
    %br
    = f.select(:experience_years, options_for_select(0..25, selected: f.object.experience_years),  {:class => 'form-control'})
  .field
    = f.label "Salary range (Drag each triangle to create the range for this position)"
    %br
    %input#salaries{:'data-slider-handle' => 'triangle'}
    = f.hidden_field :salary_low,id: 'salary_low'
    = f.hidden_field :salary_high, id: 'salary_high'
    %br
    %br
  .field
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .field
    = f.label :state
    %br
    = f.collection_select(:state_id, State.all, :id, :name,  {:class => 'form-control'})
    %br
  .field
    = f.label :zip
    = f.number_field :zip, class: 'form-control'
  .field
    %h5 Is this a telecommuting position?
    Yes
    = f.check_box :is_remote, style: 'width:15px'
    %br
    %br
  = f.submit 'Submit', class: 'btn btn-default', id: 'save-btn'
:javascript
  $(function(){
    $('#save-btn').on('click', function(){
      $('#salary_low').val(salary_slider.slider('getValue')[0]);
      $('#salary_high').val(salary_slider.slider('getValue')[1]);
    })
    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });
  });

app/views/jobs/edit.html.haml
.container.padded-container
  .account-panel
    .account-header
      %h2 Edit Job
    .account-content
      = render 'form', job: @job

app/views/jobs/employer_index.html.haml
.action-bar
  .container
    .row
      .col-md-9
        %h2 My Open Jobs
      .col-md-3.text-right
        = link_to 'Create New Job', new_job_path, class: 'btn btn-default'

.container.padded-container
  .row
    .col-md-12.job-status
      = "Open Jobs (#{@jobs.count})"
      |
      = link_to "Inactive Jobs (#{@inactive_job_count})", employer_archive_jobs_path
      |
      = link_to "Expired Jobs (#{@expired_job_count})", employer_job_expired_path
      %hr

  -@jobs.each do |job|
    .row
      .col-md-8
        %h3= link_to job.title, job_path(job)
        %p= strip_tags(truncate(job.description, length: 600, omission: "...", escape: false))
        .stat
          = link_to employer_show_actions_path(job) do
            %i.fa.fa-inbox
            %span
            = list_job_viewed_by_visible_candidates(job).count
            views
        .stat
          = link_to employer_show_matches_path(job) do
            %i.fa.fa-search
            %span
            = job.candidate_matches_list.count
            matches
        .stat
          = link_to employer_show_path(job) do
            %i.fa.fa-inbox
            = job.applicants.count
            applicants
        .stat
          = link_to employer_show_shortlists_path(job) do
            %i.fa.fa-list-ol
            = job.shortlist.count
            shortlist
        .stat
          = link_to employer_show_remove_path(job) do
            %i.fa.fa-close
            = job.deleted.count
            removed
      .col-md-4.job-actions
        = link_to new_job_path(:copy_id => job.id), class: "btn btn-info" do
          %i.fa.fa-plus{title: "copy to a new job"}
          Copy
        = link_to edit_job_path(job), class: "btn btn-info" do
          %i.fa.fa-edit{title: "edit this job"}
          Edit
        = link_to inactivate_job_path(job), class: "btn btn-info", :method => :put, :data => { :confirm => 'Are you sure?' } do
          %i.fa.fa-trash{title: "inactivate this job"}
          Inactivate
    %hr
  = paginate @jobs
  - if @jobs.count === 0
    %h3.text-center
      Looks like you haven't created any jobs yet. <br> Get started by
      = link_to "creating your first job.", new_job_path

app/views/jobs/employer_show.html.haml
.candidate-matches
  .action-bar
    .container
      .row
        .col-md-12
          %h2= @job.title

  .container.padded-container
    .row
      .col-md-12
        %h2{style: 'padding-bottom:5px'}
          Applicants
          %hr
        - if @job_candidates.present?
          - @job_candidates.each do |job_candidate|
            = link_to candidates_profile_path(job_candidate.candidate) do
              .row
                .col-md-2
                  %img{src: job_candidate.candidate.candidate_profile.avatar_url}
                .col-md-6
                  %h3
                    = job_candidate.candidate.name
                  = get_location job_candidate.candidate.candidate_profile
                .col-md-4
                  %h4 Education
                  - if job_candidate.candidate.candidate_profile.education_level
                    = job_candidate.candidate.candidate_profile.education_level.name
            .row
              .col-md-6
              - if job_candidate.is_applicants?
                .col-md-2
                  = link_to accept_candidate_path(job_candidate.id), method: :put do
                    %button.btn.btn-default.force-form-button#hire{style: 'width: 128px'}
                      %i.fa.fa-check
                      Accept
                .col-md-2
                  = form_tag(remove_candidate_path(@job, job_candidate.candidate), method: 'post') do
                    %button.btn.btn-default.force-form-button
                      %i.fa.fa-close
                      Remove
                .col-md-2
                  = form_tag(shortlist_candidate_path(@job, job_candidate.candidate), method: 'post') do
                    %button.btn.btn-default.force-form-button
                      %i.fa.fa-list-ol
                      Shortlist
              - elsif job_candidate.withdrawn?
                .col-md-3
                  %h4
                    Application Withdrawn
              - elsif job_candidate.accepted?
                .col-md-3
                  %h4
                    Match Accepted
          = paginate @job_candidates
        - else
          %h3.text-center
            There are no applicants yet.

app/views/jobs/employer_show_actions.html.haml
.candidate-matches
  .action-bar
    .container
      .row
        .col-md-12
          %h2= @job.title

  .container.padded-container
    .row
      .col-md-12
        %h2{style: 'padding-bottom:5px'}
          Candidate Views
          %hr
        %table.table.table-responsive
          - if @candidates.present?
            - @candidates.includes(:candidate_profile => [:state, :education_level]).each do |candidate|
              = link_to candidates_profile_path(candidate) do
                .row
                  .col-md-2
                    %img{src: candidate.candidate_profile.avatar_url}
                  .col-md-6
                    %h3
                      = candidate.name
                    = get_location candidate.candidate_profile
                  .col-md-4
                    %h4 Education
                    - if candidate.candidate_profile.education_level
                      = candidate.candidate_profile.education_level.name
                %hr
            = paginate @candidates
          - else
            %h3.text-center
              No one has viewed this job yet...come back soon!

app/views/jobs/employer_show_matches.html.haml
.candidate-matches
  .action-bar
    .container
      .row
        .col-md-12
          %h2
            = @job.title
  .container.padded-container
    .row
      .col-md-6
        %h2{style: 'padding-bottom:5px'}
          %span Candidate Matches
      - if @job.is_active && @candidates.present?
        .col-md-6
          %div.mail-matched
            = form_tag email_match_candidates_job_path(@job), method: :post do
              = submit_tag "Email matched candidates", class: 'btn btn-md btn-info'
    %hr
    .row
      .col-md-12
        %table.table.table-responsive
          - if @candidates.present?
            - @candidates.includes(:candidate_profile => [:state, :education_level]).each do |candidate|
              .row
                .col-md-2
                  = link_to candidates_profile_path(candidate) do
                    %img{src: candidate.candidate_profile.avatar_url}
                .col-md-6
                  = link_to candidates_profile_path(candidate) do
                    %h3
                      = candidate.name
                    = get_location candidate.candidate_profile
                  %br
                  %br
                  %p
                    = mail_to candidate.email, "Email Candidate"
                .col-md-4
                  %h4 Education
                  - if candidate.candidate_profile.education_level
                    = candidate.candidate_profile.education_level.name
              %hr
            = paginate @candidates
          - else
            %h3.text-center
              There are no candidate matches yet. Come back soon!

app/views/jobs/employer_show_shortlists.html.haml
.candidate-matches
  .action-bar
    .container
      .row
        .col-md-12
          %h2= @job.title

  .container.padded-container
    .row
      .col-md-12
        %h2{style: 'padding-bottom:5px'}
          Candidate Shortlist
          %hr
        %table.table.table-responsive
          - if @shortlists.present?
            - @shortlists.each do |job_candidate|
              = link_to candidates_profile_path(job_candidate.candidate) do
                .row
                  .col-md-2
                    %img{src: job_candidate.candidate.candidate_profile.avatar_url}
                  .col-md-6
                    %h3
                      - if job_candidate.candidate.candidate_profile.is_incognito
                        Candidate
                      - else
                        = job_candidate.candidate.name
                    = get_location job_candidate.candidate.candidate_profile
                  .col-md-4
                    %h4 Education
                    - if job_candidate.candidate.candidate_profile.education_level
                      = job_candidate.candidate.candidate_profile.education_level.name
              .row
                .col-md-8
                .col-md-2
                  = link_to accept_candidate_path(job_candidate.id), method: :put do
                    %button.btn.btn-default.force-form-button#hire{style: 'width: 128px'}
                      %i.fa.fa-check
                      Connect
                .col-md-2
                  = form_tag(remove_candidate_path(@job, job_candidate.candidate), method: 'post') do
                    %button.btn.btn-default{type: 'submit'}
                      %i.fa.fa-close
                      Remove
            = paginate @shortlists
          - else
            %h3.text-center
              There are currently no short-listed candidates.

app/views/jobs/index.html.haml
#job-list
  .container.padded-container
    .row
      .col-md-2
        - if candidate_signed_in?
          = render 'jobs/candidate_sidebar'
      .col-md-10
        .row
          %p= @jobs_str
          .col-md-4
            %h3 Position
          .col-md-2
            %h3 Salary
          .col-md-3
            %h3 Location
          .col-md-3
        - @jobs.each do |job|
          .row
            = link_to job_path(job) do
              .col-md-4
                %h4
                  = job.title
              .col-md-2
                %b
                  Salary Range
                %br
                = "$#{job.salary_low}"
                \-
                = "$#{job.salary_high}"
              .col-md-3
                %b
                  Location
                %br
                = "#{job.city}, #{job.state.name}"
            .col-md-3
              - if candidate_signed_in?
                = form_for(CandidateJobAction.new, html: { style: 'display:inline'}) do |f|
                  = f.hidden_field :candidate_id, value: "#{current_candidate.id}"
                  = f.hidden_field :job_id, value: "#{job.id}"
                  = f.hidden_field :is_saved, value: "true"
                  %button.btn.btn-default.float-right= "Save Position"
          %hr

app/views/jobs/list_disable_jobs.html.haml
.action-bar
  .container
    .row
      .col-md-10
        %h2 My expired jobs
      .col-md-2
        = link_to 'Create New Job', new_job_path, class: 'btn btn-default'

.container.padded-container
  .row
    .col-md-12.job-status
      = link_to "Open Jobs (#{@active_job_count})", employer_jobs_path
      |
      = link_to "Inactive Jobs (#{@inactive_job_count})", employer_archive_jobs_path
      |
      = "Expired Jobs (#{@jobs.count})"
      %hr
  - @jobs.each do |job|
    .row
      .col-md-8
        %h3= job.title
        %p= strip_tags(truncate(job.description, length: 600, omission: "...", escape: false))
      .col-md-4.job-actions
        = link_to "#", {class: 'btn btn-info',"data-target" => "#enable-job-#{job.id}", "data-toggle" => "modal", :type => "button"} do
          %i.fa.fa-rocket
          Enable
    / Modal
    .modal.fade{:role => "dialog", id: "enable-job-#{job.id}"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"data-dismiss" => "modal", :type => "button"} ×
            %h4.modal-title Pay to enable the job
          .modal-body
            %h4
              = job.title
            %p
              = strip_tags(truncate(job.description, length: 600, omission: "...", escape: false))
            %hr
            %p By clicking on "Pay and submit" button our system will automatically deduct $#{JOB_POSTING_FEE} to enable this job for next 30 days. Click on "Cancel" button to return back.
            %p 

            %hr
            
          .modal-footer
            = form_tag employer_job_payment_path(job.id) do
              = submit_tag "Pay and submit", class: "btn btn-default pull-left" 
          
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel

    %hr
  = paginate @jobs

:css
  .modal-backdrop {
    display:none;
  }

app/views/jobs/send_intro.js.haml
alert('Message successfully sent!');