config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :candidate_job_actions, only: [
                                            :candidate_job_saved,
                                            :candidate_job_viewed,
                                            :candidate_matches,
                                            :candidate_save_job
  ]

  resources :jobs do
    member do
      post :email_match_candidates
    end
  end

  resources :educations, only: [:destroy]

  resources :experiences, only: [:destroy]

  resources :job_candidates, only: [
                                      :withdrawn_job_candidates,
                                      :open_job_candidates,
                                      :receipt,
                                      :shortlist_candidate,
                                      :remove_candidate,
                                      :withdraw,
                                      :accept_candidate,
                                      :apply
                                    ]

  devise_for :employers, :controllers => { :sessions => "employers/sessions", :registrations => "employers/registrations"}
  devise_for :candidates, :controllers => { :sessions => "candidates/sessions", :registrations => "candidates/registrations"}

  get 'candidates/account' => 'candidates#account'
  put 'candidates/account' => 'candidates#update'
  get 'candidates/archetype' => 'candidates#archetype'
  get 'candidates/archetype_result' => 'candidates#archetype_result'
  put 'candidates/archetype' => 'candidates#update_archetype'
  get 'candidates/profile/:id' => 'candidates#profile', as: 'candidates_profile'
  get 'candidates/incognito' => 'candidates#incognito'
  get 'candidates/subscription' => 'candidates#subscription'

  get 'candidates/jobs_saved' => 'candidate_job_actions#candidate_job_saved', as: 'candidate_job_saved'
  get 'candidates/jobs_viewed' => 'candidate_job_actions#candidate_job_viewed', as: 'candidate_job_viewed'
  get 'candidates/candidate_matches' => 'candidate_job_actions#candidate_matches', as: 'candidate_matches'
  post 'candidates/candidate_save_job/:job_id' => 'candidate_job_actions#candidate_save_job', as: 'candidate_save_job'

  get 'my_withdrawn_jobs' => 'job_candidates#withdrawn_job_candidates'
  get 'my_jobs' => 'job_candidates#open_job_candidates'
  get 'job_receipt/:id' => 'job_candidates#receipt', as: 'job_receipt'
  post 'shortlist_candidate/:job_id/:candidate_id' => 'job_candidates#shortlist_candidate', as: 'shortlist_candidate'
  post 'remove_candidate/:job_id/:candidate_id' => 'job_candidates#remove_candidate', as: 'remove_candidate'
  put 'withdraw/:id' => 'job_candidates#withdraw', as: 'withdraw_candidate'
  put 'accept_candidate/:id' => 'job_candidates#accept_candidate', as: 'accept_candidate'
  get 'job_candidates/:id/apply' => "job_candidates#apply", as: "create_job_candidates"

  get 'employers/public/:id' => 'employers#public', as: 'employers_public'
  get 'employers/account' => 'employers#account'
  put 'employers/account' => 'employers#update'
  get 'employers/profile' => 'employers#profile'
  get 'employers/payment_methods' => 'employers#list_payment_method'
  get 'employers/payment/verify' => 'employers#add_payment_method'
  post 'employers/payment' => 'employers#insert_payment_method'
  get 'employers/choose_pay_method' => 'employers#choose_payment_method'

  get 'employer_jobs' => 'jobs#employer_index', as: 'employer_jobs'
  get 'employer_jobs/archive' => 'jobs#employer_archive', as: 'employer_archive_jobs'
  get 'employer_jobs/:id' => 'jobs#employer_show', as: 'employer_show'
  get 'employer_job_actions/:id' => 'jobs#employer_show_actions', as: 'employer_show_actions'
  get 'employer_job_matches/:id' => 'jobs#employer_show_matches', as: 'employer_show_matches'
  get 'employer_job_shortlists/:id' => 'jobs#employer_show_shortlists', as: 'employer_show_shortlists'
  get 'employer_job_remove/:id' => 'jobs#employer_show_remove', as: 'employer_show_remove'
  put 'inactivate_job/:id' => 'jobs#inactivate_job', as: 'inactivate_job'
  get 'employer_job_expired' => 'jobs#list_expired_jobs', as: 'employer_job_expired'
  post 'employer_payment/:id' => 'jobs#pay_to_enable_expired_job', as: 'employer_job_payment'

  root to: 'pages#index'
  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'hustlers' => 'pages#hustlers'
  get 'hirers_faq' => 'pages#hirers_faq'
  get 'hustlers_faq' => 'pages#hustlers_faq'
  get 'privacy_policy' => 'pages#privacy_policy'
  get 'pages/index'
  get 'pages/hustlers'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/hirers_faq'
  get 'pages/hustlers_faq'
  get 'pages/privacy_policy'

end

app/models/candidate.rb
# == Schema Information
#
# Table name: candidates
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  archetype_score        :integer
#  year_experience_id     :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#

class Candidate < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
  :recoverable, :rememberable, :trackable, :validatable

  # association
  has_one :candidate_profile, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :candidate_question_answers, dependent: :destroy
  has_many :job_candidates, dependent: :destroy
  has_many :candidate_job_actions, dependent: :destroy
  belongs_to :year_experience

  accepts_nested_attributes_for :candidate_profile
  accepts_nested_attributes_for :experiences, allow_destroy: true
  accepts_nested_attributes_for :educations, allow_destroy: true
  accepts_nested_attributes_for :candidate_question_answers, allow_destroy: true

  # validation
  validates_presence_of :first_name, :last_name

  after_save :add_candidate_profile

  def name
    return self.first_name + ' ' + self.last_name
  end

  # authorization
  def is_owner_of?(obj)
    self.id == obj.try(:candidate_id)
  end

  # authorization: use this method to check object's parent is archived or not archived
  def archived?
    self.deleted_at.present?
  end

  def has_applied(job)
    JobCandidate.where(:job_id => job.id, :candidate_id => self.id).count > 0
  end

  def job_status(job)
    JobCandidate.where(:job_id => job.id, :candidate_id => self.id).first.status
  end

  def view_job(job)
    CandidateJobAction.create job_id: job.id, candidate_id: self.id, is_saved: false
  end

  def can_proceed
    self.archetype_score
  end

  def password_required?
    super #&& provider.blank?
  end

  def email_required?
    super #&& provider.blank?
  end

  def archetype_string
    if !self.archetype_score
      return 'n/a'
    end

    # score between 71-100
    if self.archetype_score > 71
      return 'Aggressive Hunter'

    # score between 31-70
    elsif self.archetype_score > 31
      return 'Relaxed Hunter'

    # score between 11-30
    elsif self.archetype_score > 11
      return 'Aggressive Fisherman'

    # score between -10-10
    elsif self.archetype_score > -10
      return 'Balanced Fisherman'

    # score between -30-(-11)
    elsif self.archetype_score > -30
      return 'Relaxed Fisherman'

    # score between -70-(-31)
    elsif self.archetype_score > -70
      return 'Aggressive Farmer'

    # score between -100-(-71)
    else
      return 'Relaxed Farmer'
    end
  end

  # instead of deleting, indicate the candidate requested a delete
  # and timestamp it
  def archive
    update_attribute(:deleted_at, Time.current)
  end

  # ensure candidate account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  private

  def add_candidate_profile
    if self.candidate_profile.blank?
      profile = CandidateProfile.new(candidate_id: self.id)
      profile.save
    end
  end
end

app/controllers/candidates/omniauth_callbacks_controller.rb
# class Candidates::OmniauthCallbacksController < Devise::OmniauthCallbacksController
#   def linkedin
#     # You need to implement the method below in your model (e.g. app/models/user.rb)

#     @candidate = Candidate.from_omniauth(request.env["omniauth.auth"])


#     if @candidate.persisted?
#       flash.notice = "Signed in!"
#       if @candidate.flash_notice
#         flash.notice = @candidate.flash_notice
#       end
#       sign_in_and_redirect @candidate, notice: "Signed in!"
#     else
#       session["devise.candidate_attributes"] = @candidate.attributes
#       redirect_to new_candidate_registration_url
#     end
#   end
# end

app/controllers/candidates/registrations_controller.rb
class Candidates::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
  def edit
    super
  end
  def create
    super
    if candidate_signed_in?
      Question.all.each do |question|
        current_candidate.candidate_question_answers.build question_id: question.id
      end
      current_candidate.save
    end

    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.people.set('candidate-'+resource.email, {
                                                   '$email'            => resource.email,
                                                   '$first_name'       => resource.first_name
                                               });
    tracker.track('candidate-'+resource.email, 'candidate sign up')
  end
  def update
    super
  end
  def new
    super
  end
  def destroy
    resource.archive
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) } 
  end

  protected

  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name,
               :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name,
               :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/candidates/sessions_controller.rb
class Candidates::SessionsController < Devise::SessionsController
  skip_before_filter :check_candidate, only: [:destroy]
  def after_sign_in_path_for(resource)
    '/my_jobs'
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  skip_before_filter :check_candidate, only: [:archetype, :update_archetype]
  before_action :authenticate_candidate!, only: [:archetype, :account, :update,
                                                 :update_archetype, :archetype_result,
                                                 :incognito, :subscription]
  # submit archetype
  # only signed_in candidate access this
  def archetype
    authorize(current_candidate)
  end

  # view profile
  # candidate can view his profile
  # employer can view applicants profile
  # end user can view profile when incognito OFF
  def profile
    if params[:id]
      @candidate = Candidate.find(params[:id])
      @profile = @candidate.candidate_profile
      authorize(@profile)
    elsif current_candidate
      authorize(current_candidate)
      @candidate = current_candidate
      @profile = current_candidate.candidate_profile
    end
  end

  # submit profile info
  # only signed_in candidate access this
  def account
    authorize(current_candidate)
    current_candidate.build_candidate_profile if !current_candidate.candidate_profile
  end

  # update candidate, profile, education, work experiences.
  # only signed_in candidate access this
  def update
    authorize(current_candidate)
    respond_to do |format|
      if current_candidate.update(candidate_params)
        current_candidate.save
        format.html { redirect_to candidates_profile_path(current_candidate),
                      notice: 'Profile was successfully updated.' }
      else
        format.html { render :account }
      end
    end
  end

  # update archetype
  # only signed_in candidate access this
  def update_archetype
    authorize(current_candidate)
    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('candidate-'+current_candidate.email, 'updated archetype')

    respond_to do |format|
      if current_candidate.update(candidate_params)
        current_candidate.archetype_score = CandidateQuestionAnswer.calculate_archetype_score(current_candidate)
        current_candidate.save
        format.html { redirect_to candidates_archetype_result_path }
      else
        format.html { render :account }
      end
    end
  end

  # view archetype result and submit form to complete profile
  # only signed_in candidate access this
  def archetype_result
    authorize(current_candidate)
  end

  #should make a put but tired
  # Toggle incognito
  # only signed_in candidate access this
  def incognito
    authorize(current_candidate)
    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('candidate-'+current_candidate.email, 'incognito toggle')
    @profile = current_candidate.candidate_profile
    @profile.toggle!(:is_incognito)
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  # subscribe and unsubscribe to job match alert
  # only signed in candidate access this
  def subscription
    authorize(current_candidate)
    @profile = current_candidate.candidate_profile
    @profile.toggle!(:is_active_match_subscription)
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate)
            .permit(:year_experience_id, :archetype_score, :first_name, :last_name,
                    candidate_profile_attributes: [:id, :avatar, :is_incognito,
                                                   :zip, :city, :state_id, :ziggeo_token,
                                                   :education_level_id, :resume],
                                        :experiences_attributes => [:id, :position,
                                        :company, :start_date, :end_date, :description,
                                        :is_sales, :sales_type_id, :is_current, :_destroy],
                                        educations_attributes: [:id, :college_id,
                                          :college_other, :education_level_id, :description,
                                          :_destroy],
                                        candidate_question_answers_attributes: [:question_id,
                                              :id, :answer_id] )
    end
end

app/views/candidates/_candidate_question_answer_fields.html.haml
%fieldset.account-field{id: 'account-field-'+f.object.question.id.to_s, style: (f.object.question.id == 1 ? '' : 'display:none')}
  %h4= f.object.question.name
  = f.hidden_field :id, value: f.object.id
  = f.hidden_field :question_id, value: f.object.question.id
  - Answer.all.each do |answer|
    .row#answer-choice
      .col-md-1
        = f.radio_button :answer_id, answer.id, style: 'display:inline'
      .col-md-11
        = answer.name
  -if f.object.question.id != 20
    %br
    .btn.btn-default.btn-full.next_button{disabled: true}
      Next

app/views/candidates/_education_fields.html.haml
%fieldset.account-field
  = f.hidden_field :id, value: f.object.id
  = f.label "School"
  = f.collection_select(:college_id, College.all, :id, :name, {},  {:class => 'form-control college-select'})
  = f.label "Other"
  = f.text_field :college_other, disabled: true, class: 'college-other'
  = f.label "Degree"
  %br
  = f.collection_select(:education_level_id, EducationLevel.all, :id, :name,  {:class => 'form-control'})
  %br
  = f.label "Description"
  = f.text_area :description, class: 'form-control'
  = f.hidden_field :_destroy, class: 'remove-object'
  = link_to "remove", class: "remove_fields btn btn-primary pull-right" do
    %i.fa.fa-trash
    Remove
  %br
  %br
  %br
  %hr
:javascript
  $('.college-select').on("change", function(){
    if ($($(this).find('option:selected')).text() == "Other"){
      $(this).parent().find(".college-other").attr("disabled", false);
    }else{
      $(this).parent().find(".college-other").attr("disabled", true);
      $(this).parent().find(".college-other").val('');
    }
  });

app/views/candidates/_education_item.html.haml
.row
  .col-md-10
    %h4
      - if education.college
        - if education.college_other && education.college_other != ''
          = education.college_other
        - else
          = education.college.name
    %p
      = education.education_level.name
    %p
      = format_date education.start_date
      \-
      = format_date education.end_date
    %p
      = education.description
  .col-md-2
    - if current_candidate
      = link_to "X", education_path(education.id), method: :delete, data: { confirm: 'Do you want to remove this record?' }, class: 'btn btn-sm btn-danger'
%hr

app/views/candidates/_experience_item.html.haml
.row
  .col-md-10
    %h4
      = experience.position
    %p
      = experience.company
    %small
      = format_date experience.start_date
      - if !experience.is_current
        \-
        = format_date experience.end_date
      - else
        \- currently employed
    %p
      = experience.description

  .col-md-2
    - if current_candidate
      = link_to "X", experience_path(experience.id), method: :delete, data: { confirm: 'Do you want to remove this record?' }, class: 'btn btn-sm btn-danger'

%hr
  

app/views/candidates/_incognito.html.haml
- if profile.is_incognito
  %br
  %br
  %p Your profile is currently hidden. Turn off incognito mode to make your profile public.
- else
  %br
  %br
  %p Your profile is currently visible. Turn on incognito mode to hide your profile.
%br
%br

app/views/candidates/account.html.haml
#registration-bar
  .container
    .row
      .col-md-4
        .btn.btn-primary.profile#accounts
          Profile
      .col-md-4
        .btn.btn-primary.profile#experience
          Experience
      .col-md-4
        .btn.btn-primary.profile#education
          Education

.container.padded-container
  #account
    #new-registration
      = form_for(current_candidate, validate: true, url: candidates_account_path, html: { multipart: true, method: :put }) do |f|

        // Account Page
        #accounts-panel.account-panel
          .account-header
            %h2 Profile Information
          .account-content
            .text-center
              In a minute-length video below, please introduce yourself, tell us about your sales background and share what makes you a valuable asset to an organization. Sell yourself!
            %br
            %hr
            %br
            = f.fields_for :candidate_profile do |profile_fields|
              = f.label :first_name
              = f.text_field :first_name, class: 'form-control'
              = f.label :last_name
              = f.text_field :last_name, class: 'form-control'
              = render 'profile_fields', profile_fields: profile_fields
              .video-container
                .row
                  .col-md-6
                    %ziggeo{ 'ziggeo-width' => 320, 'ziggeo-height' => 240 }
                  .col-md-5.col-md-offset-1
                    %p Please introduce yourself and talk about your sales experience. Tell us about your top three accomplishments and why you are in sales. Let your passion shine through! Your video should be no more than one-minute long. Keep it concise. Feel free to re-record as many times as you need to!
              %br
              .btn.btn-default.btn-full.next_button#experience-button
                Next

        // Experience Page
        #experience-panel.account-panel{style: 'display:none'}
          .account-header
            %h2 Work Experience
            %i.fa.fa-info-circle.info{title: "add your work experience"}
          .account-content
            .text-center
              Please list any previous positions you’ve held, starting with your most recent job.
            %br
            %hr
            %br
            = f.fields_for :experiences do |builder|
              = render 'experience_fields', f: builder
              %hr
            = link_to_add_fields "+ Add Experience", f, :experiences
            %br
            %br
            .btn.btn-default.btn-full.next_button#education-button
              Next

        // Education Page
        #education-panel.account-panel{style: 'display:none'}
          .account-header
            %h2 Education Experience
            %i.fa.fa-info-circle.info{title: "add your education experience"}
          .account-content
            .text-center
              Now, let's work on your education history. Start by listing your highest degree obtained, and then work down to your high school education.
            %br
            %hr
            %br
            = f.fields_for :educations do |builder|
              = render 'education_fields', f: builder
            = link_to_add_fields "+ Add Education", f, :educations
            %br
            %br
            %button.btn.btn-default.btn-full
              Submit

:javascript
  function account(){
    $('.profile').on('click',function(){
      $('.profile').removeClass('btn-active');
      $('.account-panel').hide();
      $('#'+this.id+'-panel').show();
      $(this).addClass('btn-active');
    });

    $('.next_button').on('click',function(){
      $('.profile').removeClass('btn-active');
      $('.account-panel').hide();
      $('#'+this.id.split('-')[0]+'-panel').show();
      $('#'+this.id.split('-')[0]).addClass('btn-active');
    });

    ZiggeoApi.Events.on("submitted", function (data) {
    	$('#ziggeo-token').val(data.video.token);
    });

    $('#archetype-panel').find('input').on('click',function(){
      if ($('#archetype-panel').find('input:checked').length == 20){
        $('#accounts-button').attr('disabled',false);
      }
    });

    $('.college-select').on("change", function(){
    });
  }


  $(document).on('page:load', account);
  $(document).ready(account);

app/views/candidates/archetype.html.haml
.container.padded-container
  #account
    #new-registration
      = form_for(current_candidate, validate: true, url: candidates_archetype_path, html: { multipart: true, method: :put }) do |f|

        // Archetype Page
        #archetype-panel.account-panel
          .account-header
            %h2 Sales Personality Assessment
          .account-content
            .text-left
              We are excited to have you joining us here at Salesmatchr! So we can make the best job match for your personality and expertise, we will need you to complete a brief survey. Only YOU can see the results. Understanding you sales personality aids in matching to the right type of job. Please be honest....and it only takes 5 minutes!
            %br
            %hr
            %br
            #archetype-pre
              = f.label "How much sales experience do you have?"
              = f.collection_select(:year_experience_id, YearExperience.all, :id, :name,  {:class => 'form-control selectpickers'})
              %br
              %button.btn.btn-default.btn-full#start-survey
                Start Assessment
              %br
              %i This will only take five minutes.
            #archetype-survey{style: 'display:none'}
              = f.fields_for :candidate_question_answers do |builder|
                = render 'candidate_question_answer_fields', f: builder

            %button.btn.btn-default#accounts-button{style: 'display:none'}
              Submit

:javascript
  function archetype_ready(){
    $('#archetype-panel').find('input').on('click',function(){
      $(this).parents('.account-field').find('.next_button').attr('disabled',false);
      if ($('#archetype-panel').find('input:checked').length == 20){
        $('#accounts-button').css('display','inline');
      }
    });
    $('.next_button').on('click', function(){
      current_id = $(this).parents('.account-field')[0].id.split('-')[2]
      $(this).parents('.account-field').hide();
      $('#account-field-'+(parseInt(current_id)+1)).show();
    });
    $('#start-survey').on('click', function(evt){
      $('#archetype-pre').hide();
      $('#archetype-survey').show();
      return false;
    });
  }
  $(document).ready(archetype_ready);
  $(document).on('page:load', archetype_ready);

app/views/candidates/archetype_result.html.haml
.profile

  .container.padded-container
    .row
      .col-md-12
        .center-img
          = image_tag get_archetype_image_from_score current_candidate.archetype_score
    .text-center
      %h4= get_archetype_from_score current_candidate.archetype_score
      %p
        = (get_archetype_description_from_score current_candidate.archetype_score).html_safe
      %p
        = link_to "Complete your profile", candidates_account_path, class: "btn btn-default"

app/views/candidates/incognito.js.erb
$("#incognito-toggle").html("<%= escape_javascript(render('incognito', profile: @profile)) %>");

app/views/candidates/profile.html.haml
.profile
  .container.padded-container
    - if current_candidate && current_candidate.id == @candidate.id
      .row
        .col-md-4
          .archetype-img
            = image_tag get_archetype_image_from_score @candidate.archetype_score
        .col-md-8
          %h2= @candidate.name
          %h4= get_archetype_from_score @candidate.archetype_score
          %p
            = get_archetype_description_from_score @candidate.archetype_score#.html_safe
            %br
            %br
            = link_to "Edit Profile", candidates_account_path, class: "btn btn-default"
    - else
      .text-center
        %h2= @candidate.name
    %hr
    .wrapper-sm
      .container
        .row
          - if @profile.present?
            .col-md-12.text-center
              #incognito-panel
                #incognito-header
                  Resume
                #incognito-content
                  - if @profile.resume.present?
                    = link_to "Download Resume", @profile.resume.url, class: 'btn btn-primary'
                  - else
                    Resume is not uploaded yet!
                %br
                %br
            .col-md-12.text-center
              - if current_candidate && current_candidate.id == @candidate.id
                #incognito-panel
                  #incognito-header
                    Subscribe to job match
                  #incognito-content
                    %input{:checked => "", :name => "my-checkbox", :type => "checkbox", :id => 'subscribe', checked: @profile.is_active_match_subscription}/
                    #subscription-toggle
                      = render 'subscription', profile: @profile
                  %br
                  %br
            .col-md-12.text-center
              - if current_candidate && current_candidate.id == @candidate.id
                #incognito-panel
                  #incognito-header
                    Incognito Mode
                  #incognito-content
                    %input{:checked => "", :name => "my-checkbox", :type => "checkbox", :id => 'incognito', checked: @profile.is_incognito}/
                    #incognito-toggle
                      = render 'incognito', profile: @profile
            .col-md-6
              = image_tag @profile.avatar.url(:medium), id: 'avatar', style: "display:" + (!@profile.is_incognito ? 'block' : 'none'), class: 'profile-image'
              %img{src: '/img/incognito.png', style: "display:" + (@profile.is_incognito ? 'block' : 'none'), id: 'incognito-img', class: 'profile-image'}
              - if @profile.ziggeo_token != nil && @profile.ziggeo_token != ''
                .embed-responsive-item
                  %ziggeo{ 'ziggeo-video' => @profile.ziggeo_token, 'ziggeo-responsive' => true }
                %br
              - elsif ( current_candidate == @candidate ) && ( !@profile.ziggeo_token )
                = link_to 'Edit your profile to add a video', candidates_account_path
                %br
              .account-panel
                .account-content
                  .row
                    .col-md-6
                      %h4 Location
                      %p
                        = @profile.city
                        - if @profile.state
                          = @profile.state.name
                        = @profile.zip
                    .col-md-6
                      %h4 Education Level
                      %p
                        - if @profile.education_level
                          = @profile.education_level.name
                  .row
                    .col-md-6
                      %h4 Experience
                      %p
                        - if @candidate.year_experience
                          = @candidate.year_experience.name
          // Work Experience & Education
          .col-md-6
            %div.tabpanel{:role => "tabpanel"}
              / Nav tabs
              %ul.nav.nav-tabs{:role => "tablist"}
                %li.active{:role => "presentation"}
                  %a{"aria-controls" => "work", "data-toggle" => "tab", :href => "#work", :role => "tab"} Work History
                %li{:role => "presentation"}
                  %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#education", :role => "tab"} Education
              / Tab panes
              .tab-content.account-panel
                #work.tab-pane.active{:role => "tabpanel"}
                  .account-content
                    - if @candidate.experiences == 0
                      %h2 hi
                    - else
                      - @candidate.experiences.each do |experience|
                        = render 'candidates/experience_item', experience: experience

                #education.tab-pane{:role => "tabpanel"}
                  .account-content
                    - @candidate.educations.includes([:college, :education_level]).each do |education|
                      = render 'candidates/education_item', education: education
- if @profile.present?
  :javascript
    var profile_picture_url = "#{@profile.avatar_url}";
    $(function(){
      $('#incognito').on('switchChange.bootstrapSwitch', function(event, state) {
        var url = '/candidates/incognito/'
        $.get(url)
        if (state){
          $('#avatar').hide();
          $('#incognito-img').show();
        }else{
          $('#avatar').show();
          $('#incognito-img').hide();
        }
      })
    $('#subscribe').on('switchChange.bootstrapSwitch', function(event, state) {
        var url = '/candidates/subscription/'
        $.get(url)
      })
    })
  })

app/views/candidates/subscription.js.erb
$("#subscription-toggle").html("<%= escape_javascript(render('subscription', profile: @profile)) %>");