config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :candidate_job_actions, only: [
                                            :candidate_job_saved,
                                            :candidate_job_viewed,
                                            :candidate_matches,
                                            :candidate_save_job
  ]

  resources :jobs do
    member do
      post :email_match_candidates
    end
  end

  resources :educations, only: [:destroy]

  resources :experiences, only: [:destroy]

  resources :job_candidates, only: [
                                      :withdrawn_job_candidates,
                                      :open_job_candidates,
                                      :receipt,
                                      :shortlist_candidate,
                                      :remove_candidate,
                                      :withdraw,
                                      :accept_candidate,
                                      :apply
                                    ]

  devise_for :employers, :controllers => { :sessions => "employers/sessions", :registrations => "employers/registrations"}
  devise_for :candidates, :controllers => { :sessions => "candidates/sessions", :registrations => "candidates/registrations"}

  get 'candidates/account' => 'candidates#account'
  put 'candidates/account' => 'candidates#update'
  get 'candidates/archetype' => 'candidates#archetype'
  get 'candidates/archetype_result' => 'candidates#archetype_result'
  put 'candidates/archetype' => 'candidates#update_archetype'
  get 'candidates/profile/:id' => 'candidates#profile', as: 'candidates_profile'
  get 'candidates/incognito' => 'candidates#incognito'
  get 'candidates/subscription' => 'candidates#subscription'

  get 'candidates/jobs_saved' => 'candidate_job_actions#candidate_job_saved', as: 'candidate_job_saved'
  get 'candidates/jobs_viewed' => 'candidate_job_actions#candidate_job_viewed', as: 'candidate_job_viewed'
  get 'candidates/candidate_matches' => 'candidate_job_actions#candidate_matches', as: 'candidate_matches'
  post 'candidates/candidate_save_job/:job_id' => 'candidate_job_actions#candidate_save_job', as: 'candidate_save_job'

  get 'my_withdrawn_jobs' => 'job_candidates#withdrawn_job_candidates'
  get 'my_jobs' => 'job_candidates#open_job_candidates'
  get 'job_receipt/:id' => 'job_candidates#receipt', as: 'job_receipt'
  post 'shortlist_candidate/:job_id/:candidate_id' => 'job_candidates#shortlist_candidate', as: 'shortlist_candidate'
  post 'remove_candidate/:job_id/:candidate_id' => 'job_candidates#remove_candidate', as: 'remove_candidate'
  put 'withdraw/:id' => 'job_candidates#withdraw', as: 'withdraw_candidate'
  put 'accept_candidate/:id' => 'job_candidates#accept_candidate', as: 'accept_candidate'
  get 'job_candidates/:id/apply' => "job_candidates#apply", as: "create_job_candidates"

  get 'employers/public/:id' => 'employers#public', as: 'employers_public'
  get 'employers/account' => 'employers#account'
  put 'employers/account' => 'employers#update'
  get 'employers/profile' => 'employers#profile'
  get 'employers/payment_methods' => 'employers#list_payment_method'
  get 'employers/payment/verify' => 'employers#add_payment_method'
  post 'employers/payment' => 'employers#insert_payment_method'
  get 'employers/choose_pay_method' => 'employers#choose_payment_method'

  get 'employer_jobs' => 'jobs#employer_index', as: 'employer_jobs'
  get 'employer_jobs/archive' => 'jobs#employer_archive', as: 'employer_archive_jobs'
  get 'employer_jobs/:id' => 'jobs#employer_show', as: 'employer_show'
  get 'employer_job_actions/:id' => 'jobs#employer_show_actions', as: 'employer_show_actions'
  get 'employer_job_matches/:id' => 'jobs#employer_show_matches', as: 'employer_show_matches'
  get 'employer_job_shortlists/:id' => 'jobs#employer_show_shortlists', as: 'employer_show_shortlists'
  get 'employer_job_remove/:id' => 'jobs#employer_show_remove', as: 'employer_show_remove'
  put 'inactivate_job/:id' => 'jobs#inactivate_job', as: 'inactivate_job'
  get 'employer_job_expired' => 'jobs#list_expired_jobs', as: 'employer_job_expired'
  post 'employer_payment/:id' => 'jobs#pay_to_enable_expired_job', as: 'employer_job_payment'

  root to: 'pages#index'
  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'hustlers' => 'pages#hustlers'
  get 'hirers_faq' => 'pages#hirers_faq'
  get 'hustlers_faq' => 'pages#hustlers_faq'
  get 'privacy_policy' => 'pages#privacy_policy'
  get 'pages/index'
  get 'pages/hustlers'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/hirers_faq'
  get 'pages/hustlers_faq'
  get 'pages/privacy_policy'

end

app/models/job_candidate.rb
# == Schema Information
#
# Table name: job_candidates
#
#  id           :integer          not null, primary key
#  candidate_id :integer
#  job_id       :integer
#  status       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class JobCandidate < ActiveRecord::Base
  # association
  belongs_to :job
  belongs_to :candidate

  # validation
  validates_presence_of :candidate_id, :job_id
  validates_uniqueness_of :candidate_id, scope: :job_id

  enum status: [:submitted, :viewed, :accepted, :withdrawn,
                :shortlist, :deleted]

  # method returns job_candidates record for active and enable job
  scope :active_job_candidate_list, ->(current_candidate) {
  																		where(:candidate_id => current_candidate.id)
                											.joins(:job)
                											.where('jobs.status=0 and jobs.is_active=true')}

  # method return statuses values on array             											
  def self.statuses_opened
  	arr = Array.new
  	arr << JobCandidate.statuses['submitted']
  	arr << JobCandidate.statuses['viewed']
  	arr << JobCandidate.statuses['shortlist']
  	arr << JobCandidate.statuses['accepted']
  	arr << JobCandidate.statuses['deleted']
  	return arr
  end

  # used by views
  def is_applicants?
    (self.submitted? || self.viewed?)
  end
end

app/controllers/job_candidates_controller.rb
class JobCandidatesController < ApplicationController
  before_action :authenticate_candidate!, only: [:apply, :receipt, :withdraw,
                                                 :withdrawn_job_candidates,
                                                 :open_job_candidates]
  before_action :authenticate_employer!, only: [:accept_candidate, :remove_candidate,
                                                :shortlist_candidate]
  before_action :set_job_candidate, only: [:receipt, :withdraw, :accept_candidate]
  before_action :require_candidate_profile, only: [:withdrawn_job_candidates,
                                                   :open_job_candidates, :apply]

  # return all withdrawn job candidates
  def withdrawn_job_candidates
    authorize(JobCandidate.new)
    if active_job_candidate_list.present?
      @withdrawn_job_candidates = active_job_candidate_list.includes(:job)
                                  .where(status: JobCandidate.statuses["withdrawn"])
                                  .page(params[:page])
    end
  end

  # return all job_candidates who are applicants, submitted, viewed,
  # removed, shortlisted candidates
  def open_job_candidates
    authorize(JobCandidate.new)
    if active_job_candidate_list.present?
      @open_job_candidates = active_job_candidate_list.includes(:job)
                            .where("job_candidates.status in (?)",
                                    JobCandidate.statuses_opened)
                            .page(params[:page])
    end
  end

  # Only candidate can apply on Job
  def apply
    @job = Job.find(params.permit(:id)[:id])
    authorize(@job)
    job_candidate = JobCandidate.create job_id: @job.id, candidate_id: current_candidate.id
    job_candidate.submitted!

    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('candidate-' + job_candidate.candidate.email, 'applied to job')

    EmployerMailer.send_job_application(@job.employer.email, @job).deliver_later
    redirect_to job_receipt_path(job_candidate)
  end

  # url: job_receipt/:id
  # Only candidate can access this page
  def receipt
    authorize @job_candidate
    @job = @job_candidate.job
  end

  # Candidate can withdraw job application
  # signed_in candidate is required
  def withdraw
    authorize @job_candidate
    @job_candidate.withdrawn!
    EmployerMailer.send_job_withdrawn(@job_candidate.job.employer.email, @job_candidate.job).deliver_later
    redirect_to my_jobs_path, notice: 'Successfully withdrawn.'
  end

  # signed_in employer is required
  # employer can accept candidate's application
  def accept_candidate
    authorize(@job_candidate)
    @job_candidate.accepted!
    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('employer-' + current_employer.email, 'accepted candidate')
    CandidateMailer.send_job_hire(@job_candidate.candidate.email, @job_candidate.job).deliver_later
    redirect_to employer_jobs_path, notice: 'Successfully accepted, an email was sent to the candidate.'
  end

  # This action is used by employer to remove this candidate from the job in which this candidate had applied already.
  def remove_candidate
    job_candidate = JobCandidate.where(:job_id => params[:job_id],
                                       :candidate_id => params[:candidate_id]).first
    authorize(job_candidate)
    job_candidate.status = JobCandidate.statuses[:deleted]
    job_candidate.save

    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('employer-'+current_employer.email, 'removed candidate from job')

    redirect_to employer_show_path(params[:job_id]), notice: 'Candidate removed'
  end

  # This action is used by employer to shortlist candidate who had applied to employer's job
  def shortlist_candidate
    tracker = Mixpanel::Tracker.new(ENV["NT_MIXPANEL_TOKEN"])
    tracker.track('employer-'+current_employer.email, 'shortlisted candidate')

    job_candidate = JobCandidate.where(:job_id => params[:job_id],
                                       :candidate_id => params[:candidate_id]).first
    authorize(job_candidate)
    job_candidate.status = JobCandidate.statuses[:shortlist]
    job_candidate.save

    redirect_to employer_show_path(params[:job_id]), notice: 'Candidate shortlisted'
  end

  private

  def set_job_candidate
    @job_candidate = JobCandidate.find(params[:id])
  end

  # return job_candidates of current_candidate where are jobs are active and enable
  def active_job_candidate_list
    @job_candidates = JobCandidate.active_job_candidate_list(current_candidate)
  end

  # candidate should save his profile info before applying any job of employer because employer can view candidate's profile.
  def require_candidate_profile
    unless current_candidate.candidate_profile.present?
      redirect_to candidates_account_path, notice: 'Complete your profile information'
    end
  end
end

app/views/job_candidates/open_job_candidates.html.haml
.job-list
  .action-bar
    .container
      .row
        .col-md-9
          %h2 My Open Jobs
  .container.padded-container
    .row
      .col-md-2
        %p
          = link_to "Open Jobs", my_jobs_path
        %p
          = link_to "Withdrawn Jobs", my_withdrawn_jobs_path
      .col-md-10
        - if @open_job_candidates.present?
          - if @job_candidates.count === 0
            %h3.text-center
              Looks like you haven't applied for any jobs yet. <br> Get started by
              = link_to "searching for available jobs.", jobs_path
          -	@open_job_candidates.each do |job_candidate|
            .row
              .col-md-8
                %h3= link_to job_candidate.job.title, job_path(job_candidate.job)
                %p= job_candidate.job.description
                %p
                - if job_candidate.submitted?
                  %b.secondary-color
                    Submitted
                - else
                  Submitted
                |
                - if job_candidate.viewed?
                  %b.secondary-color
                    Viewed
                - else
                  Viewed
                |
                - if job_candidate.shortlist?
                  %b.secondary-color
                    Shortlist
                - else
                  Shortlist
                |
                - if job_candidate.accepted?
                  %b.secondary-color
                    Accepted
                - else
                  Accepted
                |
                - if job_candidate.deleted?
                  %b.secondary-color
                    deleted
                - else
                  deleted
              .col-md-4.job-actions
                - if !job_candidate.withdrawn?
                  = link_to "Withdraw", withdraw_candidate_path(job_candidate.id), method: :put, data: {confirm: 'Do you want to withdraw this application?'}, class: 'button btn btn-info', id: 'hire'
                %hr

          = paginate @open_job_candidates
        - else
          No records found yet!

app/views/job_candidates/receipt.html.haml
.padded-container.container
  .row
    .col-md-12.text-center
      %h2
        You have successfully applied to
        = @job.title
        %br
      %h4
        Someone will be in contact regarding future employment
      %br
      %br
      %br
      %h4
        Discover more matches
        = link_to "here", candidate_matches_path

app/views/job_candidates/withdrawn_job_candidates.html.haml
.job-list
  .action-bar
    .container
      .row
        .col-md-9
          %h2 My Withdrawn Jobs
  .container.padded-container
    .row
      .col-md-2
        %p
          = link_to "Open Jobs", my_jobs_path
        %p
          = link_to "Withdrawn Jobs", my_withdrawn_jobs_path
      .col-md-10
        - if @withdrawn_job_candidates.present?
          - @withdrawn_job_candidates.each do |job_candidate|
            - if job_candidate.withdrawn?
              - if job_candidate.job
                .row
                  = link_to job_path(job_candidate.job) do
                    .col-md-8
                      %h3= job_candidate.job.title
                      %p= job_candidate.job.description
                  .col-md-4.job-actions
                %hr

          = paginate @withdrawn_job_candidates
        - else
          No Record found yet!