config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)

  resources :candidate_job_actions, only: [
                                            :candidate_job_saved,
                                            :candidate_job_viewed,
                                            :candidate_matches,
                                            :candidate_save_job
  ]

  resources :jobs do
    member do
      post :email_match_candidates
    end
  end

  resources :educations, only: [:destroy]

  resources :experiences, only: [:destroy]

  resources :job_candidates, only: [
                                      :withdrawn_job_candidates,
                                      :open_job_candidates,
                                      :receipt,
                                      :shortlist_candidate,
                                      :remove_candidate,
                                      :withdraw,
                                      :accept_candidate,
                                      :apply
                                    ]

  devise_for :employers, :controllers => { :sessions => "employers/sessions", :registrations => "employers/registrations"}
  devise_for :candidates, :controllers => { :sessions => "candidates/sessions", :registrations => "candidates/registrations"}

  get 'candidates/account' => 'candidates#account'
  put 'candidates/account' => 'candidates#update'
  get 'candidates/archetype' => 'candidates#archetype'
  get 'candidates/archetype_result' => 'candidates#archetype_result'
  put 'candidates/archetype' => 'candidates#update_archetype'
  get 'candidates/profile/:id' => 'candidates#profile', as: 'candidates_profile'
  get 'candidates/incognito' => 'candidates#incognito'
  get 'candidates/subscription' => 'candidates#subscription'

  get 'candidates/jobs_saved' => 'candidate_job_actions#candidate_job_saved', as: 'candidate_job_saved'
  get 'candidates/jobs_viewed' => 'candidate_job_actions#candidate_job_viewed', as: 'candidate_job_viewed'
  get 'candidates/candidate_matches' => 'candidate_job_actions#candidate_matches', as: 'candidate_matches'
  post 'candidates/candidate_save_job/:job_id' => 'candidate_job_actions#candidate_save_job', as: 'candidate_save_job'

  get 'my_withdrawn_jobs' => 'job_candidates#withdrawn_job_candidates'
  get 'my_jobs' => 'job_candidates#open_job_candidates'
  get 'job_receipt/:id' => 'job_candidates#receipt', as: 'job_receipt'
  post 'shortlist_candidate/:job_id/:candidate_id' => 'job_candidates#shortlist_candidate', as: 'shortlist_candidate'
  post 'remove_candidate/:job_id/:candidate_id' => 'job_candidates#remove_candidate', as: 'remove_candidate'
  put 'withdraw/:id' => 'job_candidates#withdraw', as: 'withdraw_candidate'
  put 'accept_candidate/:id' => 'job_candidates#accept_candidate', as: 'accept_candidate'
  get 'job_candidates/:id/apply' => "job_candidates#apply", as: "create_job_candidates"

  get 'employers/public/:id' => 'employers#public', as: 'employers_public'
  get 'employers/account' => 'employers#account'
  put 'employers/account' => 'employers#update'
  get 'employers/profile' => 'employers#profile'
  get 'employers/payment_methods' => 'employers#list_payment_method'
  get 'employers/payment/verify' => 'employers#add_payment_method'
  post 'employers/payment' => 'employers#insert_payment_method'
  get 'employers/choose_pay_method' => 'employers#choose_payment_method'

  get 'employer_jobs' => 'jobs#employer_index', as: 'employer_jobs'
  get 'employer_jobs/archive' => 'jobs#employer_archive', as: 'employer_archive_jobs'
  get 'employer_jobs/:id' => 'jobs#employer_show', as: 'employer_show'
  get 'employer_job_actions/:id' => 'jobs#employer_show_actions', as: 'employer_show_actions'
  get 'employer_job_matches/:id' => 'jobs#employer_show_matches', as: 'employer_show_matches'
  get 'employer_job_shortlists/:id' => 'jobs#employer_show_shortlists', as: 'employer_show_shortlists'
  get 'employer_job_remove/:id' => 'jobs#employer_show_remove', as: 'employer_show_remove'
  put 'inactivate_job/:id' => 'jobs#inactivate_job', as: 'inactivate_job'
  get 'employer_job_expired' => 'jobs#list_expired_jobs', as: 'employer_job_expired'
  post 'employer_payment/:id' => 'jobs#pay_to_enable_expired_job', as: 'employer_job_payment'

  root to: 'pages#index'
  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'hustlers' => 'pages#hustlers'
  get 'hirers_faq' => 'pages#hirers_faq'
  get 'hustlers_faq' => 'pages#hustlers_faq'
  get 'privacy_policy' => 'pages#privacy_policy'
  get 'pages/index'
  get 'pages/hustlers'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/hirers_faq'
  get 'pages/hustlers_faq'
  get 'pages/privacy_policy'

end

app/views/layouts/_footer.html.haml
#footer
  .container
    .row
      .col-md-3
        %h4 SALESMATCHR
        %ul
          %li
            Salesmatchr Inc.<br>
            1900 Campus Commons Drive, Suite 100<br>
            Reston,  VA  20191
          %li
            %i.fa.fa-envelope
            team@salesmatchr.com
          %li
            %i.fa.fa-phone
            (703) 224-8088
          %li.social
            = link_to 'https://www.facebook.com/salesmatchr' do
              %i.fa.fa-facebook
            = link_to 'https://twitter.com/salesmatchr' do
              %i.fa.fa-twitter
      .col-md-3
        %h4 MORE SALESMATCHR
        %ul
          /%li
          /= link_to "Blog", 'https://salesmatchrblog.wordpress.com/'
          %li
            = link_to "Contact Us", "mailto:support@salesmatchr.com"
      .col-md-3
        %h4 RESOURCES
        %ul
          %li Terms of Service
          %li Privacy Policy
          %li
            = link_to "Hustler FAQ", pages_hustlers_faq_path
          %li
            = link_to "Hirer FAQ", pages_hirers_faq_path
      .col-md-3
        %a.twitter-timeline{"data-widget-id" => "636603275060604928", :href => "https://twitter.com/salesmatchr"} Tweets by @salesmatchr

:javascript
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/layouts/_mixpanel_script.html.haml
/ start Mixpanel
:javascript
  (function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
  0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
  for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
  mixpanel.init("577282eccac5b3456d3b97c9f2b44fc8");
/ end Mixpanel

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SalesMatchr
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    /%link{:type => "text/css", :rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"}
    /%link{:type => "text/css", :rel => "stylesheet", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
    /%link{:type => "text/css", :rel => "stylesheet", :href => 'http://fonts.googleapis.com/css?family=Open+Sans' }
    /%link{:type => "text/css", :rel => "stylesheet", :href => 'http://fonts.googleapis.com/css?family=Shadows+Into+Light' }
    %link{:type => "text/css", rel:"stylesheet", href:"//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" }
    /%link{:type => "text/css", :rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap2/bootstrap-switch.min.css" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    /%script{:type => "text/javascript", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"}
    /%script{:type => "text/javascript", :src => "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js"}
    /%script{type:"text/javascript", src: "https://js.stripe.com/v2/"}
    = tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY
    = csrf_meta_tags
    = render "layouts/mixpanel_script"
  %body

  %nav.navbar
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-brand
          = link_to '/' do
            = image_tag 'salesmatchr-logo-white.png'
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if candidate_signed_in?
            %li
              = link_to 'Job Matches', jobs_path
            %li
              = link_to "My Jobs", my_jobs_path
            %li.dropdown
              %button#dropdownMenu1.dropdown-toggle.btn{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
                = current_candidate.first_name
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu"}
                %li
                  = link_to 'Profile', candidates_profile_path(current_candidate)
                %li
                  = link_to "Settings", edit_candidate_registration_path
                %li
                  = link_to "Sign out", destroy_candidate_session_path, :method => :delete
          - elsif employer_signed_in?
            %li
              = link_to "My Jobs", employer_jobs_path
            %li.dropdown
              %button#dropdownMenu2.dropdown-toggle.btn{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}
                = current_employer.name
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu2", :role => "menu"}
                %li
                  = link_to 'My Profile', employers_profile_path(current_candidate)
                %li
                  = link_to "Settings", edit_employer_registration_path
                %li
                  = link_to "Payment method", employers_payment_methods_path
                %li
                  = link_to "Sign out", destroy_employer_session_path, :method => :delete
          - else
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Hire-ers
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  = link_to 'How It Works', root_path
                %li
                  = link_to 'FAQ', pages_hirers_faq_path
                %li
                  = link_to 'Create Your Account', new_employer_registration_path
                %li
                  = link_to "Sign in", new_employer_session_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Hustlers
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  = link_to 'How It Works', hustlers_path
                %li
                  = link_to 'FAQ', pages_hustlers_faq_path
                %li
                  = link_to 'Create Your Account', new_candidate_registration_path
                %li
                  = link_to 'Sign in', new_candidate_session_path
            /%li
            /= link_to "Blog", 'http://salesmatchrblog.com/'
            - if params[:action].in?(["hustlers", "hustlers_faq"])
              %li
                = link_to "Sign up", new_candidate_registration_path
              %li
                = link_to "Sign in", new_candidate_session_path
            - else
              %li
                = link_to "Sign up", new_employer_registration_path
              %li
                = link_to "Sign in", new_employer_session_path

  #flash-display
    .container
      - flash.each do |type, msg|
        %div{:class => "alert alert-#{type == :notice ? "success" : type} fadeout", "data-dismiss" => "alert"}
          %button.close &times;
          .text-center= msg if msg.is_a?(String)
  = yield
  = render 'layouts/footer'